Traceback (most recent call last):
  File "/home/yblee/jb/.venv/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/yblee/jb/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/yblee/jb/.venv/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/yblee/jb/.venv/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/yblee/jb/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/yblee/jb/.venv/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
pd.DataFrame([['hi', 'there'], ['this', 'is'], ['a', 'DataFrame']], columns=['Word A', 'Word B'])
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[6], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[1;32m      2[0m pd[38;5;241m.[39mDataFrame([[[38;5;124m'[39m[38;5;124mhi[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mthere[39m[38;5;124m'[39m], [[38;5;124m'[39m[38;5;124mthis[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mis[39m[38;5;124m'[39m], [[38;5;124m'[39m[38;5;124ma[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mDataFrame[39m[38;5;124m'[39m]], columns[38;5;241m=[39m[[38;5;124m'[39m[38;5;124mWord A[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mWord B[39m[38;5;124m'[39m])

[0;31mModuleNotFoundError[0m: No module named 'pandas'

