Traceback (most recent call last):
  File "/home/runner/work/tdc/tdc/.venv/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/work/tdc/tdc/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/work/tdc/tdc/.venv/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/work/tdc/tdc/.venv/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/runner/work/tdc/tdc/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/work/tdc/tdc/.venv/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pymysql
from sqlalchemy import create_engine, text
# conn = pymysql.connect(host='localhost',
#                              user='admin',
#                              password='admin1234',
#                              db='STOCKDB',
#                              charset='utf8')

engine = create_engine('mysql+pymysql://admin:admin1234@localhost/STOCKDB')
connn = engine.connect()
# curs = conn.cursor()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mConnectionRefusedError[0m                    Traceback (most recent call last)
File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/pymysql/connections.py:616[0m, in [0;36mConnection.connect[0;34m(self, sock)[0m
[1;32m    615[0m [38;5;28;01mtry[39;00m:
[0;32m--> 616[0m     sock [38;5;241m=[39m [43msocket[49m[38;5;241;43m.[39;49m[43mcreate_connection[49m[43m([49m
[1;32m    617[0m [43m        [49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mhost[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mport[49m[43m)[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mconnect_timeout[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m
[1;32m    618[0m [43m    [49m[43m)[49m
[1;32m    619[0m     [38;5;28;01mbreak[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/socket.py:845[0m, in [0;36mcreate_connection[0;34m(address, timeout, source_address)[0m
[1;32m    844[0m [38;5;28;01mtry[39;00m:
[0;32m--> 845[0m     [38;5;28;01mraise[39;00m err
[1;32m    846[0m [38;5;28;01mfinally[39;00m:
[1;32m    847[0m     [38;5;66;03m# Break explicitly a reference cycle[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/socket.py:833[0m, in [0;36mcreate_connection[0;34m(address, timeout, source_address)[0m
[1;32m    832[0m     sock[38;5;241m.[39mbind(source_address)
[0;32m--> 833[0m [43msock[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43msa[49m[43m)[49m
[1;32m    834[0m [38;5;66;03m# Break explicitly a reference cycle[39;00m

[0;31mConnectionRefusedError[0m: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

[0;31mOperationalError[0m                          Traceback (most recent call last)
File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py:145[0m, in [0;36mConnection.__init__[0;34m(self, engine, connection, _has_events, _allow_revalidate, _allow_autobegin)[0m
[1;32m    144[0m [38;5;28;01mtry[39;00m:
[0;32m--> 145[0m     [38;5;28mself[39m[38;5;241m.[39m_dbapi_connection [38;5;241m=[39m [43mengine[49m[38;5;241;43m.[39;49m[43mraw_connection[49m[43m([49m[43m)[49m
[1;32m    146[0m [38;5;28;01mexcept[39;00m dialect[38;5;241m.[39mloaded_dbapi[38;5;241m.[39mError [38;5;28;01mas[39;00m err:

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py:3288[0m, in [0;36mEngine.raw_connection[0;34m(self)[0m
[1;32m   3267[0m [38;5;250m[39m[38;5;124;03m"""Return a "raw" DBAPI connection from the connection pool.[39;00m
[1;32m   3268[0m 
[1;32m   3269[0m [38;5;124;03mThe returned object is a proxied version of the DBAPI[39;00m
[0;32m   (...)[0m
[1;32m   3286[0m 
[1;32m   3287[0m [38;5;124;03m"""[39;00m
[0;32m-> 3288[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mpool[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py:452[0m, in [0;36mPool.connect[0;34m(self)[0m
[1;32m    445[0m [38;5;250m[39m[38;5;124;03m"""Return a DBAPI connection from the pool.[39;00m
[1;32m    446[0m 
[1;32m    447[0m [38;5;124;03mThe connection is instrumented such that when its[39;00m
[0;32m   (...)[0m
[1;32m    450[0m 
[1;32m    451[0m [38;5;124;03m"""[39;00m
[0;32m--> 452[0m [38;5;28;01mreturn[39;00m [43m_ConnectionFairy[49m[38;5;241;43m.[39;49m[43m_checkout[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py:1267[0m, in [0;36m_ConnectionFairy._checkout[0;34m(cls, pool, threadconns, fairy)[0m
[1;32m   1266[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m fairy:
[0;32m-> 1267[0m     fairy [38;5;241m=[39m [43m_ConnectionRecord[49m[38;5;241;43m.[39;49m[43mcheckout[49m[43m([49m[43mpool[49m[43m)[49m
[1;32m   1269[0m     [38;5;28;01mif[39;00m threadconns [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py:716[0m, in [0;36m_ConnectionRecord.checkout[0;34m(cls, pool)[0m
[1;32m    715[0m [38;5;28;01melse[39;00m:
[0;32m--> 716[0m     rec [38;5;241m=[39m [43mpool[49m[38;5;241;43m.[39;49m[43m_do_get[49m[43m([49m[43m)[49m
[1;32m    718[0m [38;5;28;01mtry[39;00m:

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py:169[0m, in [0;36mQueuePool._do_get[0;34m(self)[0m
[1;32m    168[0m [38;5;28;01mexcept[39;00m:
[0;32m--> 169[0m     [38;5;28;01mwith[39;00m util[38;5;241m.[39msafe_reraise():
[1;32m    170[0m         [38;5;28mself[39m[38;5;241m.[39m_dec_overflow()

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py:147[0m, in [0;36msafe_reraise.__exit__[0;34m(self, type_, value, traceback)[0m
[1;32m    146[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m
[0;32m--> 147[0m     [38;5;28;01mraise[39;00m exc_value[38;5;241m.[39mwith_traceback(exc_tb)
[1;32m    148[0m [38;5;28;01melse[39;00m:

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py:167[0m, in [0;36mQueuePool._do_get[0;34m(self)[0m
[1;32m    166[0m [38;5;28;01mtry[39;00m:
[0;32m--> 167[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_create_connection[49m[43m([49m[43m)[49m
[1;32m    168[0m [38;5;28;01mexcept[39;00m:

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py:393[0m, in [0;36mPool._create_connection[0;34m(self)[0m
[1;32m    391[0m [38;5;250m[39m[38;5;124;03m"""Called by subclasses to create a new ConnectionRecord."""[39;00m
[0;32m--> 393[0m [38;5;28;01mreturn[39;00m [43m_ConnectionRecord[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py:678[0m, in [0;36m_ConnectionRecord.__init__[0;34m(self, pool, connect)[0m
[1;32m    677[0m [38;5;28;01mif[39;00m connect:
[0;32m--> 678[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m__connect[49m[43m([49m[43m)[49m
[1;32m    679[0m [38;5;28mself[39m[38;5;241m.[39mfinalize_callback [38;5;241m=[39m deque()

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py:902[0m, in [0;36m_ConnectionRecord.__connect[0;34m(self)[0m
[1;32m    901[0m [38;5;28;01mexcept[39;00m [38;5;167;01mBaseException[39;00m [38;5;28;01mas[39;00m e:
[0;32m--> 902[0m     [38;5;28;01mwith[39;00m util[38;5;241m.[39msafe_reraise():
[1;32m    903[0m         pool[38;5;241m.[39mlogger[38;5;241m.[39mdebug([38;5;124m"[39m[38;5;124mError on connect(): [39m[38;5;132;01m%s[39;00m[38;5;124m"[39m, e)

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py:147[0m, in [0;36msafe_reraise.__exit__[0;34m(self, type_, value, traceback)[0m
[1;32m    146[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m
[0;32m--> 147[0m     [38;5;28;01mraise[39;00m exc_value[38;5;241m.[39mwith_traceback(exc_tb)
[1;32m    148[0m [38;5;28;01melse[39;00m:

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py:898[0m, in [0;36m_ConnectionRecord.__connect[0;34m(self)[0m
[1;32m    897[0m [38;5;28mself[39m[38;5;241m.[39mstarttime [38;5;241m=[39m time[38;5;241m.[39mtime()
[0;32m--> 898[0m [38;5;28mself[39m[38;5;241m.[39mdbapi_connection [38;5;241m=[39m connection [38;5;241m=[39m [43mpool[49m[38;5;241;43m.[39;49m[43m_invoke_creator[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m
[1;32m    899[0m pool[38;5;241m.[39mlogger[38;5;241m.[39mdebug([38;5;124m"[39m[38;5;124mCreated new connection [39m[38;5;132;01m%r[39;00m[38;5;124m"[39m, connection)

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py:637[0m, in [0;36mcreate_engine.<locals>.connect[0;34m(connection_record)[0m
[1;32m    635[0m             [38;5;28;01mreturn[39;00m connection
[0;32m--> 637[0m [38;5;28;01mreturn[39;00m [43mdialect[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[38;5;241;43m*[39;49m[43mcargs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mcparams[49m[43m)[49m

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py:615[0m, in [0;36mDefaultDialect.connect[0;34m(self, *cargs, **cparams)[0m
[1;32m    613[0m [38;5;28;01mdef[39;00m [38;5;21mconnect[39m([38;5;28mself[39m, [38;5;241m*[39mcargs, [38;5;241m*[39m[38;5;241m*[39mcparams):
[1;32m    614[0m     [38;5;66;03m# inherits the docstring from interfaces.Dialect.connect[39;00m
[0;32m--> 615[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mloaded_dbapi[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[38;5;241;43m*[39;49m[43mcargs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mcparams[49m[43m)[49m

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/pymysql/connections.py:352[0m, in [0;36mConnection.__init__[0;34m(self, user, password, host, database, unix_socket, port, charset, sql_mode, read_default_file, conv, use_unicode, client_flag, cursorclass, init_command, connect_timeout, read_default_group, autocommit, local_infile, max_allowed_packet, defer_connect, auth_plugin_map, read_timeout, write_timeout, bind_address, binary_prefix, program_name, server_public_key, ssl, ssl_ca, ssl_cert, ssl_disabled, ssl_key, ssl_verify_cert, ssl_verify_identity, compress, named_pipe, passwd, db)[0m
[1;32m    351[0m [38;5;28;01melse[39;00m:
[0;32m--> 352[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/pymysql/connections.py:668[0m, in [0;36mConnection.connect[0;34m(self, sock)[0m
[1;32m    667[0m         [38;5;28mprint[39m(exc[38;5;241m.[39mtraceback)
[0;32m--> 668[0m     [38;5;28;01mraise[39;00m exc
[1;32m    670[0m [38;5;66;03m# If e is neither DatabaseError or IOError, It's a bug.[39;00m
[1;32m    671[0m [38;5;66;03m# But raising AssertionError hides original error.[39;00m
[1;32m    672[0m [38;5;66;03m# So just reraise it.[39;00m

[0;31mOperationalError[0m: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")

The above exception was the direct cause of the following exception:

[0;31mOperationalError[0m                          Traceback (most recent call last)
Cell [0;32mIn[3], line 10[0m
[1;32m      3[0m [38;5;66;03m# conn = pymysql.connect(host='localhost',[39;00m
[1;32m      4[0m [38;5;66;03m#                              user='admin',[39;00m
[1;32m      5[0m [38;5;66;03m#                              password='admin1234',[39;00m
[1;32m      6[0m [38;5;66;03m#                              db='STOCKDB',[39;00m
[1;32m      7[0m [38;5;66;03m#                              charset='utf8')[39;00m
[1;32m      9[0m engine [38;5;241m=[39m create_engine([38;5;124m'[39m[38;5;124mmysql+pymysql://admin:admin1234@localhost/STOCKDB[39m[38;5;124m'[39m)
[0;32m---> 10[0m connn [38;5;241m=[39m [43mengine[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m
[1;32m     11[0m [38;5;66;03m# curs = conn.cursor()[39;00m

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py:3264[0m, in [0;36mEngine.connect[0;34m(self)[0m
[1;32m   3241[0m [38;5;28;01mdef[39;00m [38;5;21mconnect[39m([38;5;28mself[39m) [38;5;241m-[39m[38;5;241m>[39m Connection:
[1;32m   3242[0m [38;5;250m    [39m[38;5;124;03m"""Return a new :class:`_engine.Connection` object.[39;00m
[1;32m   3243[0m 
[1;32m   3244[0m [38;5;124;03m    The :class:`_engine.Connection` acts as a Python context manager, so[39;00m
[0;32m   (...)[0m
[1;32m   3261[0m 
[1;32m   3262[0m [38;5;124;03m    """[39;00m
[0;32m-> 3264[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_connection_cls[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py:147[0m, in [0;36mConnection.__init__[0;34m(self, engine, connection, _has_events, _allow_revalidate, _allow_autobegin)[0m
[1;32m    145[0m         [38;5;28mself[39m[38;5;241m.[39m_dbapi_connection [38;5;241m=[39m engine[38;5;241m.[39mraw_connection()
[1;32m    146[0m     [38;5;28;01mexcept[39;00m dialect[38;5;241m.[39mloaded_dbapi[38;5;241m.[39mError [38;5;28;01mas[39;00m err:
[0;32m--> 147[0m         [43mConnection[49m[38;5;241;43m.[39;49m[43m_handle_dbapi_exception_noconnection[49m[43m([49m
[1;32m    148[0m [43m            [49m[43merr[49m[43m,[49m[43m [49m[43mdialect[49m[43m,[49m[43m [49m[43mengine[49m
[1;32m    149[0m [43m        [49m[43m)[49m
[1;32m    150[0m         [38;5;28;01mraise[39;00m
[1;32m    151[0m [38;5;28;01melse[39;00m:

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py:2426[0m, in [0;36mConnection._handle_dbapi_exception_noconnection[0;34m(cls, e, dialect, engine, is_disconnect, invalidate_pool_on_disconnect, is_pre_ping)[0m
[1;32m   2424[0m [38;5;28;01melif[39;00m should_wrap:
[1;32m   2425[0m     [38;5;28;01massert[39;00m sqlalchemy_exception [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[0;32m-> 2426[0m     [38;5;28;01mraise[39;00m sqlalchemy_exception[38;5;241m.[39mwith_traceback(exc_info[[38;5;241m2[39m]) [38;5;28;01mfrom[39;00m [38;5;21;01me[39;00m
[1;32m   2427[0m [38;5;28;01melse[39;00m:
[1;32m   2428[0m     [38;5;28;01massert[39;00m exc_info[[38;5;241m1[39m] [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py:145[0m, in [0;36mConnection.__init__[0;34m(self, engine, connection, _has_events, _allow_revalidate, _allow_autobegin)[0m
[1;32m    143[0m [38;5;28;01mif[39;00m connection [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    144[0m     [38;5;28;01mtry[39;00m:
[0;32m--> 145[0m         [38;5;28mself[39m[38;5;241m.[39m_dbapi_connection [38;5;241m=[39m [43mengine[49m[38;5;241;43m.[39;49m[43mraw_connection[49m[43m([49m[43m)[49m
[1;32m    146[0m     [38;5;28;01mexcept[39;00m dialect[38;5;241m.[39mloaded_dbapi[38;5;241m.[39mError [38;5;28;01mas[39;00m err:
[1;32m    147[0m         Connection[38;5;241m.[39m_handle_dbapi_exception_noconnection(
[1;32m    148[0m             err, dialect, engine
[1;32m    149[0m         )

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py:3288[0m, in [0;36mEngine.raw_connection[0;34m(self)[0m
[1;32m   3266[0m [38;5;28;01mdef[39;00m [38;5;21mraw_connection[39m([38;5;28mself[39m) [38;5;241m-[39m[38;5;241m>[39m PoolProxiedConnection:
[1;32m   3267[0m [38;5;250m    [39m[38;5;124;03m"""Return a "raw" DBAPI connection from the connection pool.[39;00m
[1;32m   3268[0m 
[1;32m   3269[0m [38;5;124;03m    The returned object is a proxied version of the DBAPI[39;00m
[0;32m   (...)[0m
[1;32m   3286[0m 
[1;32m   3287[0m [38;5;124;03m    """[39;00m
[0;32m-> 3288[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mpool[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py:452[0m, in [0;36mPool.connect[0;34m(self)[0m
[1;32m    444[0m [38;5;28;01mdef[39;00m [38;5;21mconnect[39m([38;5;28mself[39m) [38;5;241m-[39m[38;5;241m>[39m PoolProxiedConnection:
[1;32m    445[0m [38;5;250m    [39m[38;5;124;03m"""Return a DBAPI connection from the pool.[39;00m
[1;32m    446[0m 
[1;32m    447[0m [38;5;124;03m    The connection is instrumented such that when its[39;00m
[0;32m   (...)[0m
[1;32m    450[0m 
[1;32m    451[0m [38;5;124;03m    """[39;00m
[0;32m--> 452[0m     [38;5;28;01mreturn[39;00m [43m_ConnectionFairy[49m[38;5;241;43m.[39;49m[43m_checkout[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py:1267[0m, in [0;36m_ConnectionFairy._checkout[0;34m(cls, pool, threadconns, fairy)[0m
[1;32m   1259[0m [38;5;129m@classmethod[39m
[1;32m   1260[0m [38;5;28;01mdef[39;00m [38;5;21m_checkout[39m(
[1;32m   1261[0m     [38;5;28mcls[39m,
[0;32m   (...)[0m
[1;32m   1264[0m     fairy: Optional[_ConnectionFairy] [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[1;32m   1265[0m ) [38;5;241m-[39m[38;5;241m>[39m _ConnectionFairy:
[1;32m   1266[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m fairy:
[0;32m-> 1267[0m         fairy [38;5;241m=[39m [43m_ConnectionRecord[49m[38;5;241;43m.[39;49m[43mcheckout[49m[43m([49m[43mpool[49m[43m)[49m
[1;32m   1269[0m         [38;5;28;01mif[39;00m threadconns [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m   1270[0m             threadconns[38;5;241m.[39mcurrent [38;5;241m=[39m weakref[38;5;241m.[39mref(fairy)

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py:716[0m, in [0;36m_ConnectionRecord.checkout[0;34m(cls, pool)[0m
[1;32m    714[0m     rec [38;5;241m=[39m cast(_ConnectionRecord, pool[38;5;241m.[39m_do_get())
[1;32m    715[0m [38;5;28;01melse[39;00m:
[0;32m--> 716[0m     rec [38;5;241m=[39m [43mpool[49m[38;5;241;43m.[39;49m[43m_do_get[49m[43m([49m[43m)[49m
[1;32m    718[0m [38;5;28;01mtry[39;00m:
[1;32m    719[0m     dbapi_connection [38;5;241m=[39m rec[38;5;241m.[39mget_connection()

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py:169[0m, in [0;36mQueuePool._do_get[0;34m(self)[0m
[1;32m    167[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_create_connection()
[1;32m    168[0m [38;5;28;01mexcept[39;00m:
[0;32m--> 169[0m     [38;5;28;01mwith[39;00m util[38;5;241m.[39msafe_reraise():
[1;32m    170[0m         [38;5;28mself[39m[38;5;241m.[39m_dec_overflow()
[1;32m    171[0m     [38;5;28;01mraise[39;00m

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py:147[0m, in [0;36msafe_reraise.__exit__[0;34m(self, type_, value, traceback)[0m
[1;32m    145[0m     [38;5;28;01massert[39;00m exc_value [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[1;32m    146[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m
[0;32m--> 147[0m     [38;5;28;01mraise[39;00m exc_value[38;5;241m.[39mwith_traceback(exc_tb)
[1;32m    148[0m [38;5;28;01melse[39;00m:
[1;32m    149[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/pool/impl.py:167[0m, in [0;36mQueuePool._do_get[0;34m(self)[0m
[1;32m    165[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_inc_overflow():
[1;32m    166[0m     [38;5;28;01mtry[39;00m:
[0;32m--> 167[0m         [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_create_connection[49m[43m([49m[43m)[49m
[1;32m    168[0m     [38;5;28;01mexcept[39;00m:
[1;32m    169[0m         [38;5;28;01mwith[39;00m util[38;5;241m.[39msafe_reraise():

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py:393[0m, in [0;36mPool._create_connection[0;34m(self)[0m
[1;32m    390[0m [38;5;28;01mdef[39;00m [38;5;21m_create_connection[39m([38;5;28mself[39m) [38;5;241m-[39m[38;5;241m>[39m ConnectionPoolEntry:
[1;32m    391[0m [38;5;250m    [39m[38;5;124;03m"""Called by subclasses to create a new ConnectionRecord."""[39;00m
[0;32m--> 393[0m     [38;5;28;01mreturn[39;00m [43m_ConnectionRecord[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py:678[0m, in [0;36m_ConnectionRecord.__init__[0;34m(self, pool, connect)[0m
[1;32m    676[0m [38;5;28mself[39m[38;5;241m.[39m__pool [38;5;241m=[39m pool
[1;32m    677[0m [38;5;28;01mif[39;00m connect:
[0;32m--> 678[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m__connect[49m[43m([49m[43m)[49m
[1;32m    679[0m [38;5;28mself[39m[38;5;241m.[39mfinalize_callback [38;5;241m=[39m deque()

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py:902[0m, in [0;36m_ConnectionRecord.__connect[0;34m(self)[0m
[1;32m    900[0m     [38;5;28mself[39m[38;5;241m.[39mfresh [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m    901[0m [38;5;28;01mexcept[39;00m [38;5;167;01mBaseException[39;00m [38;5;28;01mas[39;00m e:
[0;32m--> 902[0m     [38;5;28;01mwith[39;00m util[38;5;241m.[39msafe_reraise():
[1;32m    903[0m         pool[38;5;241m.[39mlogger[38;5;241m.[39mdebug([38;5;124m"[39m[38;5;124mError on connect(): [39m[38;5;132;01m%s[39;00m[38;5;124m"[39m, e)
[1;32m    904[0m [38;5;28;01melse[39;00m:
[1;32m    905[0m     [38;5;66;03m# in SQLAlchemy 1.4 the first_connect event is not used by[39;00m
[1;32m    906[0m     [38;5;66;03m# the engine, so this will usually not be set[39;00m

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py:147[0m, in [0;36msafe_reraise.__exit__[0;34m(self, type_, value, traceback)[0m
[1;32m    145[0m     [38;5;28;01massert[39;00m exc_value [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[1;32m    146[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m
[0;32m--> 147[0m     [38;5;28;01mraise[39;00m exc_value[38;5;241m.[39mwith_traceback(exc_tb)
[1;32m    148[0m [38;5;28;01melse[39;00m:
[1;32m    149[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/pool/base.py:898[0m, in [0;36m_ConnectionRecord.__connect[0;34m(self)[0m
[1;32m    896[0m [38;5;28;01mtry[39;00m:
[1;32m    897[0m     [38;5;28mself[39m[38;5;241m.[39mstarttime [38;5;241m=[39m time[38;5;241m.[39mtime()
[0;32m--> 898[0m     [38;5;28mself[39m[38;5;241m.[39mdbapi_connection [38;5;241m=[39m connection [38;5;241m=[39m [43mpool[49m[38;5;241;43m.[39;49m[43m_invoke_creator[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m
[1;32m    899[0m     pool[38;5;241m.[39mlogger[38;5;241m.[39mdebug([38;5;124m"[39m[38;5;124mCreated new connection [39m[38;5;132;01m%r[39;00m[38;5;124m"[39m, connection)
[1;32m    900[0m     [38;5;28mself[39m[38;5;241m.[39mfresh [38;5;241m=[39m [38;5;28;01mTrue[39;00m

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/engine/create.py:637[0m, in [0;36mcreate_engine.<locals>.connect[0;34m(connection_record)[0m
[1;32m    634[0m         [38;5;28;01mif[39;00m connection [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    635[0m             [38;5;28;01mreturn[39;00m connection
[0;32m--> 637[0m [38;5;28;01mreturn[39;00m [43mdialect[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[38;5;241;43m*[39;49m[43mcargs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mcparams[49m[43m)[49m

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py:615[0m, in [0;36mDefaultDialect.connect[0;34m(self, *cargs, **cparams)[0m
[1;32m    613[0m [38;5;28;01mdef[39;00m [38;5;21mconnect[39m([38;5;28mself[39m, [38;5;241m*[39mcargs, [38;5;241m*[39m[38;5;241m*[39mcparams):
[1;32m    614[0m     [38;5;66;03m# inherits the docstring from interfaces.Dialect.connect[39;00m
[0;32m--> 615[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mloaded_dbapi[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[38;5;241;43m*[39;49m[43mcargs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mcparams[49m[43m)[49m

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/pymysql/connections.py:352[0m, in [0;36mConnection.__init__[0;34m(self, user, password, host, database, unix_socket, port, charset, sql_mode, read_default_file, conv, use_unicode, client_flag, cursorclass, init_command, connect_timeout, read_default_group, autocommit, local_infile, max_allowed_packet, defer_connect, auth_plugin_map, read_timeout, write_timeout, bind_address, binary_prefix, program_name, server_public_key, ssl, ssl_ca, ssl_cert, ssl_disabled, ssl_key, ssl_verify_cert, ssl_verify_identity, compress, named_pipe, passwd, db)[0m
[1;32m    350[0m     [38;5;28mself[39m[38;5;241m.[39m_sock [38;5;241m=[39m [38;5;28;01mNone[39;00m
[1;32m    351[0m [38;5;28;01melse[39;00m:
[0;32m--> 352[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m

File [0;32m~/work/tdc/tdc/.venv/lib/python3.10/site-packages/pymysql/connections.py:668[0m, in [0;36mConnection.connect[0;34m(self, sock)[0m
[1;32m    666[0m     [38;5;28;01mif[39;00m DEBUG:
[1;32m    667[0m         [38;5;28mprint[39m(exc[38;5;241m.[39mtraceback)
[0;32m--> 668[0m     [38;5;28;01mraise[39;00m exc
[1;32m    670[0m [38;5;66;03m# If e is neither DatabaseError or IOError, It's a bug.[39;00m
[1;32m    671[0m [38;5;66;03m# But raising AssertionError hides original error.[39;00m
[1;32m    672[0m [38;5;66;03m# So just reraise it.[39;00m
[1;32m    673[0m [38;5;28;01mraise[39;00m

[0;31mOperationalError[0m: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

